### ISSUE TITLE
Resume button doesn't work

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#10]
Pausing a print works, and the pause.g file is executed if it is present. But the print can't be resumed. When the resume button is pressed, resume.g is executed if it is present, but then the print hangs. It can be paused again.

**Comment by chrishamm** [comment]
Please check again with latest DCS+FW versions - works on my setup.

**Comment by chrishamm** [comment]
Closing this issue - if the problem persists, feel free to reopen.
