### ISSUE TITLE
M27 Error?

### ISSUE THREAD

**Issue by defux** [chrishamm/DuetSoftwareFramework#101]
While printing one of the .gcode files already uploaded on SD, I pause and send M27 to receive current byte offset, I get:

M27: Not SD printing.

**Comment by chrishamm** [comment]
Thanks for the report, at present M27 works only while a print is actually live. I'll change that in the next version.

**Comment by chrishamm** [comment]
It's fixed in DSF 1.2.3.1. M26 had a similar problem and should be fixed, too.
