### ISSUE TITLE
Not getting a results message after G32 completes

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#108]
Not getting a message when G32 bed levelling completes.  I see a debug message in the DCS log...
`Completed G30 P2 X230 Y-222 Z-99999 S3 ; probe near a leadscrew and calibrate 3 motors => Leadscrew adjustments made: 0.021 0.058 0.015, points used 3, (mean, deviation) before (0.030, 0.018) after (-0.000, 0.000)`

But no actual message with the results.  There appears to be a "calibration" entry in the model now but it doesn't have the actual leadscrew adjustments.

**Comment by chrishamm** [comment]
Fixed in DSF 1.3.1, closing again.
