### ISSUE TITLE
GCode commands and parameters should be case-insensitive

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#11]
GCode should be case-insensitive, except in particular contexts e.g. quoted strings. However, a macro file using lower case command letters and parameter letters does not execute. Example of a file that does nothing:

m106 p3 s1
g1 x100 f1200
m106 p3 s0
g1 x0 f1200

**Comment by chrishamm** [comment]
Fixed in DCS 1.0.2.0.
