### ISSUE TITLE
DCS 2.0.0: Race condition between RRF and DCS restarts on M999

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#120]
If you issue an M999 (or press the "Emergency Stop" button DWC), the DCS shuts down before RRF has come back up.  With no access to config.g, RRF sits in "Off" state with no way to recover other than pressing the physical reset button on the Duet after DCS is available again.  Or, of course, changing the DCS "NoTerminateOnReset" to true so you can issue another M999 without restarting DCS.

**Comment by gtjoseph** [comment]
Additional comments...
https://forum.duet3d.com/topic/15634/should-m999-terminate-the-dsf-core-application/38

**Comment by chrishamm** [comment]
Thanks, that will be fixed in DSF 2.1.0.

**Comment by gtjoseph** [comment]
Seems to be fixed in latest commit.
