### ISSUE TITLE
DCS 2.0.0 incorrect M20 S2 response

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#121]
The response to the M20 S2 commands is incorrect in the following respects:
1. M20 S2 with no P parameter returns e.g.:
{"dir":null,"first":0,"files":["PAtestCube.gcode","TestWAB.gcode","SlowSquare.g","EscherLizardModified.gcode","TestXYZ.gcode"],"next":0,"err":0}
It has correctly defaulted the directory to 0:/gcodes, however this should be reflected in the returned "dir" property as well by returning "dir":"0:/gcodes/". Instead it returns "dir":null.
2. M20 S2 is supposed to flag each directory in the returned list with a leading asterisk. For example, M20 S2 P"0:/" returns:
{"dir":"0:/","first":0,"files":["firmware","www","gcodes","macros","filaments","sys"],"next":0,"err":0}
but it should return:
{"dir":"0:/","first":0,"files":["*firmware","*www","*gcodes","*macros","*filaments","*sys"],"next":0,"err":0}

**Comment by chrishamm** [comment]
Thanks for the note, both will be fixed in DSF 2.1.0.
