### ISSUE TITLE
DCS 2.0.0 M36 incorrect default path

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#122]
The default path used by the M36 command is supposed to be the folder where GCode print files are normally stored, which for RepRapFirmware is "0:/gcodes". However, this doesn't appear to be the case in DCS. For example, command M36 "EscherLizardModified.gcode" returns {"err":1} whereas command M36 0:/gcodes/EscherLizardModified.gcode returns the correct information.

**Comment by chrishamm** [comment]
Thanks, I'll fix it in DSF 2.1.0.
