### ISSUE TITLE
DCS Pre-2.1.1: Slowdown printing complex shapes

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#125]
With commit d993bf2cf5d9efcfed8d51fe94bb84b0df72f578 I'm getting stop-start stuttering while printing complex curves at higher speeds.  Not like the earlier pauses but more like something isn't keeping up.  Reverting to 2.1.0 fixes the issue.

**Comment by gtjoseph** [comment]
Oops.  I was printing a model for someone else and there was a large screw thread I didn't see which was causing the stop-start.  Nothing to see here.  Move along. :)

**Comment by chrishamm** [comment]
No worries, always good to see you testing! :)
