### ISSUE TITLE
'fileId' member of GCodeMachineState not being set by M98 command from DWC

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#13]
If a M98 command is issued from USB then the fileId member of GCodeMachineState gets set. However, if the M98 command is sent form the GCodeConsole in DWC then the fileId member is not set. In consequence, GCodeBuffer::IsDoingFile() incorrectly returns false.

**Comment by dc42** [comment]
See also issue #1

**Comment by chrishamm** [comment]
Fixed in the latest DCS version because it no longer interprets M98 independently from RRF. Instead, it lets M98 invoke a nested macro which ensures this flag is set correctly.
