### ISSUE TITLE
DCS 2.1.3: M117 Not parsing string replacements

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#131]
When:
 `M117 { "Axis " ^ ( move.axes[0].letter ) ^ " not homed. Please wait while all axes are homed" }`
is executed from a Duet3 serial console the following message is received:
`Axis X not homed. Please wait while all axes are homed`

When the same command is executed via DCS, the following message is received:
`{ "Axis " ^ ( move.axes[0].letter ) ^ " not homed. Please wait while all axes are homed" }`

M291 does seem to work.
`M291 P{ "Axis " ^ (move.axes[0].letter) ^ " not homed. Continue?"} R"Check axis" S1`
 executed via DCS does cause a popup with `Axis X not homed. Continue?`

**Comment by chrishamm** [comment]
This is a bug in RRF that will be adressed in the next version.

**Comment by chrishamm** [comment]
Definitely fixed in v2.2.0.
