### ISSUE TITLE
DCS 2.1.3: the "iterations" meta command is not handled correctly

### ISSUE THREAD

**Issue by bluesign2k** [chrishamm/DuetSoftwareFramework#132]
The "iterations" meta command variable isn't handled correctly when using a D3+SBC setup. This was discovered when attempting to use the example object identification macro posted by dc42 [here](https://forum.duet3d.com/topic/15648/macro-to-assist-with-using-object-cancellation/1).
The provided macro example works as intended when the D3 is used in standalone mode, but returns an error in a D3+SBC setup - see [this post](https://forum.duet3d.com/topic/15648/macro-to-assist-with-using-object-cancellation/11) for further details.

**Comment by chrishamm** [comment]
Thanks, I'll fix it in the next version. You can work-around this problem by putting expressions in square brackets into curly brackets like

```
move.axes[{iterations}].homed
```

**Comment by chrishamm** [comment]
Fixed in v2.2.0.
