### ISSUE TITLE
DCS 2.2.1-pre: CodeConsole doesn't get messages sent by M118

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#139]
`M118 S"test"` goes everywhere except CodeConsole, even if you issue the command from CodeConsole.  Very minor issue.  All other channels get the message.

**Comment by chrishamm** [comment]
It isn't supposed to, that's what the `messages` array in the OM is intended for. To output messages in the code console, use the `echo` command. This is something I already tried to explain in #118 (see https://github.com/chrishamm/DuetSoftwareFramework/issues/118#issuecomment-615254418)
