### ISSUE TITLE
M291 does not work

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#20]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`

`M291`  does not show a message/jog dialog in DWC.

This also breaks `G29` and `G32` if Z probe is set to manual via `M558 P0`. In these cases the head will just continue moving in the defined sequence and does not stop to let the user jog to the correct position.

**Comment by chrishamm** [comment]
M291+M292 is fixed in DCS 1.0.3.1. I have not tested manual Z probing yet but I expect it will work well.
