### ISSUE TITLE
Assigned filaments are not restored

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#21]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`

After a reset the filaments assigned to an extruder are not restored from `/sys/filaments.csv`. Since many people (me included) do put filament-specific configuration into the associated `/filaments/*/config.g` this can lead to prints failing.

**Comment by chrishamm** [comment]
Fixed in DCS 1.0.3.1.
