### ISSUE TITLE
Fast-clicked multi-line commands from DWC are executed out-of-order

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#23]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`
`DWC`: 2.0.0RC7
`DWS`: 1.0.0.3

If you click e.g. a jog button in DWC faster than it takes for each click to execute fully it will happen that the associated codes are executed out of order. Since jog buttons switch temporarily to relative positions, move the head and switch back to absolute positions this can lead to the axis moving to absolute 10mm instead of increasing the current position by 10mm because one of the later move commands is executed before its corresponding relative-movements command.

**Comment by chrishamm** [comment]
Should be fixed in the latest DCS version 1.0.2.0.

**Comment by T3P3** [comment]
related to #39

**Comment by chrishamm** [comment]
Fixed in DCS 1.0.3.1.
