### ISSUE TITLE
Commands from DWC while printing lead to stop

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#24]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`
`DWC`: 2.0.0RC7
`DWS`: 1.0.0.3

If a print is started any command sent from DWC while the print is running will lead to the print stopping at whatever command it is a few seconds after the DWC-issued command was executed. The printer does no longer react to any commands from DWC after that.

Restarting `DCS` is the only solution to gain back control.

**Comment by chrishamm** [comment]
Fixed in the latest RRF version, check out https://chrishamm.io/Duet3Firmware.bin
