### ISSUE TITLE
Heaters shut off while printing

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#25]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`
`DWC`: 2.0.0RC7
`DWS`: 1.0.0.3

While printing all heaters will be shut-off without any further notice after a couple of minutes. Trying to re-enable them via DWC leads to the print failing because of #24.

**Comment by chrishamm** [comment]
Do you get any particular message when this happens? I haven't encountered this problem before.

**Comment by wilriker** [comment]
No, unfortunately no message regarding heaters at all. Also nothing heater related in `DCS` log output. I will retry with 1.0.2.1 probably end of next week to see if I can provide some more information.

**Comment by chrishamm** [comment]
I still cannot reproduce this even though I ran various test prints today. I suggest you enable debugging for GCodes, Heat and perhaps LinuxInterface via M111 and check if you can discover anything new.

**Comment by wilriker** [comment]
Since I reported this there was no combination of me having the time to print something and having a workable firmware/DSF combination at the same time. I will probably retest this today.

**Comment by wilriker** [comment]
Just completed the first successful print. I close this and reopen if it ever happens again.
