### ISSUE TITLE
M111 results in 19 separate messages

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#26]
`DCS`: 1.0.1.0
`RRF`: `70b8084b0d713001e5594d570107d854269562bc`
`DWC`: 2.0.0RC7
`DWS`: 1.0.0.3

Issuing `M111` to see the status of debugging will return 19 separate messages popping up in `DWC`. One for each module plus one for the header lines (enabled/disabled modules).

**Comment by chrishamm** [comment]
Fixed in the latest RRF version.
