### ISSUE TITLE
DCS blocks after executing a macro

### ISSUE THREAD

**Issue by wilriker** [chrishamm/DuetSoftwareFramework#28]
`DCS`: 1.0.2.1
`DWS`: 1.0.1.1
`DWC`: 2.0.0-RC8-b1
`RRF`: `1c85904a`

When clicking a macro in `DWC` this will be executed but then `DCS` is blocked (on this channel?). In logging it also states it finished the macro but no more commands are accepted. Restarting `DCS` fixes the problem.

EDIT: `DCS` never returns the information that the macro has been executed to `DWC`. `DWC` continues showing a spinner and once `DCS` is being restarted it will show an error pop-up that executing the macro failed (though it actually executed).

**Comment by chrishamm** [comment]
Please share the macro file that leads to this problem. Running G28, which invokes homeall.g, works without problems on my setup.

**Comment by wilriker** [comment]
It's simply a macro called `Motors_Off` that contains
```
M84
```
and nothing else.

**Comment by wilriker** [comment]
I just found out that the Emergency Stop button is still working even in this blocked state.

**Comment by wilriker** [comment]
This is fixed in `DCS` 1.0.2.2.
