### ISSUE TITLE
estop interrupt stack issue

### ISSUE THREAD

**Issue by techildllc** [chrishamm/DuetSoftwareFramework#3]
1. Execute any macro, system or user created (ie. homex, home all)
2. WHILE macro is in progress click emergency stop.
3. When duet reboots and is idle, macros no longer work, they will hang. 
4. Another emergency stop cycle is required for everything to work again.

**Comment by chrishamm** [comment]
Might be related to #5

**Comment by chrishamm** [comment]
Should be fixed in the latest versions (1.0.1.0).
