### ISSUE TITLE
DWC requires reload after board reset

### ISSUE THREAD

**Issue by T3P3** [chrishamm/DuetSoftwareFramework#37]
duetcontrolserver 1.0.2.2
duetruntime 1.0.2.1
duetsoftwareframework 1.0.2.1
duetwebcontrol 2.0.0-2
duetwebserver 1.0.1.1

Issue: The Extrude/Retract buttons do not work in DWC after an emergency stop until DWC is reloaded (normally by refreshing the page using F5)

How to recreate: Use emergency stop to reset the Duet. Once the reset has completed ensure the hotend is up to temperature, then prese Extruder/Retract. No commands will be sent to DCS (and DWS does not report the button presses). Refresh the page (F5) try Extrude/Retract again. The commands are now sent to DWS->DCS.

**Comment by wilriker** [comment]
I can confirm this.

**Comment by chrishamm** [comment]
Fixed in DCS 1.0.3.1.
