### ISSUE TITLE
Spurious Motor(#) temp high 

### ISSUE THREAD

**Issue by techildllc** [chrishamm/DuetSoftwareFramework#4]
Server control terminal will spuriously report "high temperature reported by driver(s) X" These often occur after an estop or some sort of restart. Those motors are often not even involved in the movement and sometimes not even connect, just configured.

Running an M122 immediately after warning does not show any stepper driver issue.

**Comment by chrishamm** [comment]
AFAIK this is has been fixed in the upcoming RRFv3 version thanks to David. The new RRF beta will be released together with the next DSF bundle.

**Comment by techildllc** [comment]
Ok perfect, will test when ready and report back.

**Comment by dc42** [comment]
Believed fixed in RRF 2019-07-02b2.

**Comment by chrishamm** [comment]
Closing. If it is still present, feel free to reopen.
