### ISSUE TITLE
M98 parsing error

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#40]
Command M98 P"config.g" sent from DWC works. Command M98 Pconfig.g doesn't work and reports "File Pconfig.g not found". Interestingly, command M98 P"a.g" where file a.g doesn't exist reports "Fila Pa.g not found" instead of "File a.g not found".

**Comment by chrishamm** [comment]
Will be fixed in the next DCS version.

**Comment by chrishamm** [comment]
Fixed in DCS 1.0.3.1.
