### ISSUE TITLE
When in Subscription Patch Connection, model is not updated

### ISSUE THREAD

**Issue by mavilarino** [chrishamm/DuetSoftwareFramework#44]
In release 1.0.2.2, we are connecting to the DCS using a subscription patch connection. We have observed that the DCS sends the first full update of the Model, but it doesn't send any further patch updates unless any other client connects to the DCS with a patch connection (for example opening the DWS web page). In previous releases we didn't have this problem.

**Comment by chrishamm** [comment]
I will be happy to release DSF 1.0.2.2 (1.0.3.0) soon but I am afraid I cannot test it in depth at the moment so I am holding it off. I expect this problem will be fixed in that version.
