### ISSUE TITLE
Job start/end messages missing

### ISSUE THREAD

**Issue by dc42** [chrishamm/DuetSoftwareFramework#6]
RRF on Duet 2 writes messages to the GCode console (and the log file if logging is enabled) when a SD card job is started and when it finishes or is cancelled. These messages are not generated on Duet 3. DSF will need to generate them because it has control of the start/stop process.

**Comment by chrishamm** [comment]
These messages are shown on my setup. Please check again with the latest DCS+FW versions.

**Comment by chrishamm** [comment]
Closing this issue - if the problem persists, feel free to reopen.
