### ISSUE TITLE
DWC jog step formatting fails if changing the sign

### ISSUE THREAD

**Issue by beikeland** [chrishamm/DuetSoftwareFramework#61]
As using this for CNC I tried changing the Z jog direction so the left hand buttons would be towards the origin, and the right hand buttons away from the origin by entering a negative value for the right hand buttons. While this achieve the desired effect the formatting broke with showing both signs on the right side and no signs on the left side.

![image](https://user-images.githubusercontent.com/2701678/64685263-fb664300-d486-11e9-85ce-61bac4b8c408.png)

I guess DWC should reject negative values or fix the formatting.

**Comment by chrishamm** [comment]
I'll fix negative jog values in DWC 2.0.1. Thanks for your report!

**Comment by chrishamm** [comment]
Fixed in v2.0.1.
