### ISSUE TITLE
Need an UPGRADE note about the new socket name

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#82]
Changed from /var/run/duet.sock to /var/run/dsf/dcs.sock
If users have customized their http.json file, they'll need to ensure that they change the SocketPath accordingly.

**Comment by chrishamm** [comment]
That's a good idea, thanks

**Comment by chrishamm** [comment]
Hmm, I've been thinking about it and I don't believe there is any need to supply an extra upgrade note. If the config is unchanged, it is overwritten during an upgrade and if it was changed, the user is prompted to react to the change.
