### ISSUE TITLE
Need a way to clear the model "job" object

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#85]
...say after a cancel.  Right now you'll see the last job run until you start a new one,

This could be in the form of a http request, a new m-code, or even a new option on M0.

**Comment by chrishamm** [comment]
With DSF 1.2 and later you can create your own HTTP requests as part of a plugin and modify the machine model via LockMachineModel/SetMachineModel/UnlockMachineModel. I see no need in providing an extra way to clear those details.

**Comment by chrishamm** [comment]
Thinking about it, it will make sense to reset the Job.File object when a print has finished. I'll change that in the next version.
