### ISSUE TITLE
random g1 codes out of order DSF 1.2.1.0

### ISSUE THREAD

**Issue by daavery** [chrishamm/DuetSoftwareFramework#91]
see https://forum.duet3d.com/topic/13527/unstable-movement-in-x-y-with-latest-beta
 test gcode files and M111P3S1 results from 2 runs of the gcode linked there

**Comment by chrishamm** [comment]
I've got a fix ready but I still need to test. I'll reply to the thread when I can confirm it's working

**Comment by chrishamm** [comment]
Fixed in DSF 1.2.2.
