### ISSUE TITLE
frequency and duration swapped

### ISSUE THREAD

**Issue by beikeland** [chrishamm/DuetSoftwareFramework#92]
https://github.com/chrishamm/DuetSoftwareFramework/blob/a973c983631abf38dd12f25e99d8f468f0ab2ec3/src/DuetControlServer/Model/Updater.cs#L359

ref https://forum.duet3d.com/post/123705

**Comment by chrishamm** [comment]
Thanks, I'll fix it

**Comment by chrishamm** [comment]
Fixed in DSF 1.2.2.
